compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

# set the minimal age of npm packages to 10080 (7 days)
npmMinimalAgeGate: 10080

yarnPath: .yarn/releases/yarn-4.10.3.cjs
