#!/bin/bash
set -e

cp ../xmtp-node-go/pkg/message/v1/message.proto src/proto/

(
  cd dev/protoc
  docker build -t xmtp/protoc .
)

docker run --rm -it -v${PWD}:/code xmtp/protoc -I=src/proto --grpc-gateway-ts_out=src/proto message.proto
