name: Report a bug
description: Report a bug to share an issue you're experiencing.
title: 'Bug: '
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Community contributions like yours are key to the development and adoption of XMTP. Review the following guidelines for reporting a bug:
          - Include 1 bug per issue. Creating 1 issue per bug will make it easier to assign and track progress on bugs.
          - Check [existing issues](https://github.com/xmtp/xmtp-js/issues) to see if your issue has already been reported.
          - Ensure that the bug is not security-related and can safely be disclosed publicly on GitHub. For information about how to report a security issue, see [Security policy](https://github.com/xmtp/xmtp-js/security/policy).
          - Follow the [XMTP code of conduct](https://github.com/xmtp/xmtp-js/blob/main/CODE_OF_CONDUCT.md).
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the issue. Attach screenshots, if applicable.
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Provide a clear and concise description of the behavior you expected. Attach screenshots, if applicable.
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the bug
      description: Provide a clear and concise description of how to reproduce the bug, including any relevant environment details such as SDK version, browser, OS, and device.
