blank_issues_enabled: true
contact_links:
  - name: Have questions about how to build with XMTP?
    url: https://community.xmtp.org/
    about: Ask your question and learn with the community in the XMTP Community Forums.
